# --- CONFIGURACIÓN LÓGICA DEL SISTEMA ---

[general]
app_name = "py-mail"
version = "0.1.0"

[mail]
# Configuración global de correo
sender_name = "Asistente Académico UPN"

[templates]
# Carpeta donde residen los .html de Jinja
base_dir = "templates"

[templates.bienvenida_alumnos]
subject = "Bienvenida al curso: {curso} - {id}"
# Nombres de archivos que deben estar en PATH_ADJUNTOS_ALUMNOS
attachments = ["Cambio de contraseña - Estudiante.pdf", "Configuración_de_Microsoft_Authenticator_Estudiante.pdf"]
attachments_path = "PATH_ADJUNTOS_ALUMNOS"
type = "student_welcome"

[templates.inicio_docentes]
subject = "Inicio de curso: {fecha_inicio} - {curso} - {id}"
attachments = ["FONT PRINCIPAL SHARP GROTESK BOOK_SEMIBOLD_ BOLD.zip", "Manual Portal Académico.pdf"]
attachments_path = "PATH_ADJUNTOS_DOCENTES"
type = "teacher_start"


[templates.informe_semanal]
subject = "Reporte semanal supervisión - {fecha_lunes} al {fecha_domingo}"
fixed_recipient = "william.cruzado@upn.edu.pe"
type = "weekly_report"

[business_rules]
# Aquí podemos meter reglas como el límite de alumnos por correo en CCO, etc.
max_recipients_cco = 50

[content_vars]
# Enlaces generales
url_mimundo = "https://mimundo.upn.edu.pe/"
url_contacto = "https://contacto.upn.edu.pe/"
url_intranet = "https://intranet.upn.edu.pe/WebLogin/"
url_tutoriales_alumnos = "https://bit.ly/3YFhB0S"
url_tutoriales_docentes = "https://bit.ly/3YFhB0S" # Actualizar si hay uno específico

# Correos y Soporte
email_ayuda_clave = "ayudaclave@upn.edu.pe"
email_soporte_tic = "mesaayudaupn@upn.edu.pe"
whatsapp_upn = "+51 914 800 800"
whatsapp_arturo = "+51 951 750 111"

# Personal de Coordinación
coordinador_nombre = "William Cruzado"
coordinador_cargo = "Coordinador de Operaciones"
coordinador_email = "william.cruzado@upn.edu.pe"

asistente_nombre = "Diego Alvarado"
asistente_cargo = "Asistente de Operaciones"
asistente_email = "diego.alvarado@upn.edu.pe"
