# --- CONFIGURACIÓN LÓGICA DEL SISTEMA ---

[general]
app_name = "py-mail"
version = "0.1.0"

[mail]
# Configuración global de correo
sender_name = "Asistente Académico UPN"

[templates]
# Carpeta donde residen los .html de Jinja
base_dir = "templates"

[templates.bienvenida_alumnos]
subject = "Bienvenida al curso: {curso} - {id}"
# Nombres de archivos que deben estar en PATH_ADJUNTOS_ALUMNOS
attachments = ["Cambio de contraseña - Estudiante.pdf", "Configuración_de_Microsoft_Authenticator_Estudiante.pdf"]
attachments_path = "PATH_ADJUNTOS_ALUMNOS"
type = "student_welcome"

[templates.inicio_docentes]
subject = "Inicio de Clases: {curso} ({codigo_banner})"
attachments = ["manual_docente.pdf", "formato_sesion.xlsx"]
attachments_path = "PATH_ADJUNTOS_DOCENTES"
type = "teacher_start"


[templates.informe_semanal]
subject = "Informe Semanal de Sesiones - Semana {semana_del_anio}"
fixed_recipient = "william.coordinador@upn.edu.pe"
type = "weekly_report"

[business_rules]
# Aquí podemos meter reglas como el límite de alumnos por correo en CCO, etc.
max_recipients_cco = 50
